### ISSUE TITLE
MSDeploy / Webdeploy

### ISSUE THREAD

**Issue by jessehouwing** [jessehouwing/azure-pipelines-msbuild-helper-task#3]
- [x] OutputRoot
- [x] DeployTarget (Package | MsDeployPublish )
- [x] DeployOnBuild
- [x] Precompile
  - [ ] Per File
  - [ ] One Assembly
  - [ ] EnableUpdateable
- [ ] /p:PublishProfile
- [ ] /p:PublishUrl
- [ ] ExcludeApp_Data
- [ ] ExcludeFoldersFromDeployment (; separated list of folders)
- [ ] ExcludeFilesFromDeployment> (; separated list of files)

**Comment by wesmacdonald** [comment]
If I use the following options when doing a Web Deploy:

/p:DeployOnBuild=true 
/p:WebPublishMethod=Package 
/p:PackageAsSingleFile=true 
/p:SkipInvalidConfigurations=true 
/p:PackageLocation=$(build.artifactstagingdirectory)  /p:DisableAllVSGeneratedMSDeployParameter=true


Currently I have to leave these on the Build task to avoid target does not exist errors....
